version: '3'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
